"""Stage 5/7 publish: write the daily Markdown digest for GitHub Pages.

The English edition (posts/YYYY-MM-DD-tech-digest.md) is canonical; for every
extra language configured in sources.yaml a sibling file
(posts/YYYY-MM-DD-tech-digest-<code>.md) is rendered from the stored
translations, preserving the English author's voice. Localized labels and
native language names come from config/i18n.yaml (UTF-8 data); unknown
languages fall back to the English labels and text.

Every edition carries full author attribution (front-matter author +
description, visible byline, footer links) and a language switcher line, so
readers - and search engines - can move between the editions of one day.
"""

from __future__ import annotations

import logging
from datetime import date
from pathlib import Path

import yaml

from src.models import CuratedItem, utc_now

logger = logging.getLogger(__name__)

# Built-in English labels: the baseline every i18n block overrides from.
_EN_DEFAULTS = {
    "native_name": "English",
    "dir": "ltr",
    "og_locale": "en_US",
    "intro": (
        "__N__ stories from __S__ sources, ranked by coverage, "
        "community signal, and recency."
    ),
    "read_in": "Read this digest in",
    "curated_by": "Curated by",
    "footer_by": "Curated by:",
    "generated": "Auto-generated by __REPO__ on __STAMP__.",
    "source": "Source",
    "topic": "Topic",
    "coverage": "Coverage",
    "source_word": "source(s)",
    "score": "Score",
    "summary_h": "Summary",
    "take_h": "My Take",
}


def load_i18n(path: Path | str) -> dict:
    """Read config/i18n.yaml (UTF-8); missing file means English everywhere."""
    path = Path(path)
    if not path.exists():
        logger.warning("i18n file not found: %s - using English labels", path)
        return {}
    with open(path, encoding="utf-8") as stream:
        return yaml.safe_load(stream) or {}


def _labels(lang: str, i18n: dict | None) -> dict:
    """Merge label sources: built-in defaults <- i18n['en'] <- i18n[lang]."""
    merged = dict(_EN_DEFAULTS)
    for block in ((i18n or {}).get("en"), (i18n or {}).get(lang)):
        if isinstance(block, dict):
            merged.update({key: str(value) for key, value in block.items()})
    return merged


def _edition_filename(day: date, lang: str, extension: str = "md") -> str:
    """File name of one edition: en has no suffix, others get -<code>."""
    stem = f"{day.isoformat()}-tech-digest"
    if lang != "en":
        stem += f"-{lang}"
    return f"{stem}.{extension}"


def existing_editions(posts_dir: Path | str, day: date | None = None) -> list[Path]:
    """Digest files already on disk for the given day, across all editions.

    Lets the publish stage keep a day idempotent: a re-run (schedule +
    manual dispatch) sees the files and skips instead of overwriting the
    day's content with freshly sampled LLM output.
    """
    day = day or utc_now().date()
    posts_path = Path(posts_dir)
    if not posts_path.is_dir():
        return []
    return sorted(posts_path.glob(f"{day.isoformat()}-tech-digest*.md"))


def write_digest(
    items: list[CuratedItem],
    day: date | None = None,
    posts_dir: Path | str = "posts",
    author: dict | None = None,
    languages: list[str] | None = None,
    i18n: dict | None = None,
) -> Path:
    """Write the English edition plus every translated sibling.

    Returns the canonical English file path; translated files sit next to it.
    """
    if not items:
        raise ValueError("no curated items to publish")
    day = day or utc_now().date()
    posts_path = Path(posts_dir)
    posts_path.mkdir(parents=True, exist_ok=True)
    extra_languages = [
        code for code in dict.fromkeys(languages or []) if code and code != "en"
    ]
    i18n = i18n or {}

    canonical = posts_path / _edition_filename(day, "en")
    canonical.write_text(
        _render(items, day, author, "en", i18n, extra_languages, posts_path.name),
        encoding="utf-8",
    )
    logger.info("digest written: %s (%d items)", canonical, len(items))
    for lang in extra_languages:
        path = posts_path / _edition_filename(day, lang)
        path.write_text(
            _render(items, day, author, lang, i18n, extra_languages, posts_path.name),
            encoding="utf-8",
        )
        logger.info("translated digest written: %s", path)
    if extra_languages:
        logger.info(
            "editions: %d languages (%s)",
            1 + len(extra_languages),
            ", ".join(["en"] + extra_languages),
        )
    return canonical


def _render(
    items: list[CuratedItem],
    day: date,
    author: dict | None,
    lang: str,
    i18n: dict,
    languages: list[str],
    dir_name: str,
) -> str:
    """Full document for one language: front-matter, header, items, footer."""
    t = _labels(lang, i18n)
    sources = sorted({item.article.source for item in items})
    header = _header(items, day, sources, author, lang, t, i18n, languages, dir_name)
    blocks = [_item_block(index, item, lang, t) for index, item in enumerate(items, 1)]
    return header + ("\n---\n\n".join(blocks)) + "\n" + _footer(author, t)


def _header(
    items: list[CuratedItem],
    day: date,
    sources: list[str],
    author: dict | None,
    lang: str,
    t: dict,
    i18n: dict,
    languages: list[str],
    dir_name: str,
) -> str:
    """YAML front-matter (SEO fields + cover + lang) plus H1, byline, switcher."""
    name = (author or {}).get("name") or ""
    linkedin = (author or {}).get("linkedin") or ""
    title = f"Tech Digest - {day.isoformat()}" + (f" | {name}" if name else "")
    description = (
        f"Daily tech news digest for {day.isoformat()}: {len(items)} top stories "
        "summarized with expert commentary"
        + (f", curated by {name}." if name else ".")
    )
    author_line = f'author: "{name}"\n' if name else ""
    cover = next((item.article.image_url for item in items if item.article.image_url), None)
    cover_line = f'cover: "{cover}"\n' if cover else ""
    intro = t["intro"].replace("__N__", str(len(items))).replace("__S__", str(len(sources)))
    return (
        "---\n"
        f'title: "{title}"\n'
        f"date: {day.isoformat()}\n"
        f"items: {len(items)}\n"
        f"sources: [{', '.join(sources)}]\n"
        f"{cover_line}"
        f"lang: {lang}\n"
        f"dir: {t['dir']}\n"
        f"og_locale: {t['og_locale']}\n"
        f"{_translations_front_matter(day, lang, languages, i18n, dir_name)}"
        f"{author_line}"
        f'description: "{description}"\n'
        "generator: tech-news-curator\n"
        "---\n\n"
        f"# Tech Digest - {day.isoformat()}\n\n"
        f"_{intro}_\n\n"
        + _byline(name, linkedin, t)
        + _switcher(day, lang, languages, i18n)
    )


def _translations_front_matter(
    day: date, lang: str, languages: list[str], i18n: dict, dir_name: str,
) -> str:
    """On the English edition only: sibling files for the Jekyll index page."""
    if lang != "en" or not languages:
        return ""
    lines = ["translations:"]
    for code in languages:
        native = _labels(code, i18n)["native_name"]
        file_url = f"{dir_name}/{_edition_filename(day, code, 'html')}"
        lines.append(f'  - {{code: {code}, name: "{native}", file: "{file_url}"}}')
    return "\n".join(lines) + "\n"


def _switcher(day: date, lang: str, languages: list[str], i18n: dict) -> str:
    """'Read this digest in: ...' cross-links between the editions of one day."""
    codes = ["en"] + [code for code in languages if code != "en"]
    links = []
    for code in codes:
        if code == lang:
            continue
        native = _labels(code, i18n)["native_name"]
        links.append(f"[{native}]({_edition_filename(day, code, 'html')})")
    if not links:
        return ""
    read_in = _labels(lang, i18n)["read_in"]
    return f"**{read_in}:** " + " | ".join(links) + "\n\n"


def _byline(name: str, linkedin: str, t: dict) -> str:
    """Visible curator line near the top of the page (strong SEO placement)."""
    if not name:
        return ""
    if linkedin:
        return f"_{t['curated_by']} [{name}]({linkedin})_\n\n"
    return f"_{t['curated_by']} {name}_\n\n"


def _item_block(index: int, item: CuratedItem, lang: str, t: dict) -> str:
    """One numbered story: linked title, lead image, meta line, summary, take."""
    article = item.article
    translation = (item.translations or {}).get(lang) or {}
    title = translation.get("title") or article.title
    summary = translation.get("summary") or item.llm_summary
    take = translation.get("take") or item.personal_take
    topic = article.meta.get("category", "general")
    coverage = article.meta.get("coverage", 1)
    parts = [
        f"## {index}. [{title}]({article.url})\n\n",
        _image_markdown(article, title),
        f"**{t['source']}:** {article.source}  |  **{t['topic']}:** {topic}  |  "
        f"**{t['coverage']}:** {coverage} {t['source_word']}  |  "
        f"**{t['score']}:** {item.rank_score:.1f}\n\n"
        f"**{t['summary_h']}**\n\n"
        f"{summary}\n\n"
        f"**{t['take_h']}**\n\n"
        f"{_blockquote(take)}\n",
    ]
    return "".join(parts)


def _image_markdown(article, alt_title: str | None = None) -> str:
    """Markdown image for the story lead, or an empty string when it has none."""
    url = article.image_url
    if not url:
        return ""
    alt = _safe_alt(alt_title or article.title)
    destination = _safe_destination(url)
    return f"![{alt}]({destination})\n\n"


def _safe_alt(title: str) -> str:
    """Keep the title from breaking the ![alt] brackets."""
    return title.replace("[", "(").replace("]", ")").replace('"', "'")


def _safe_destination(url: str) -> str:
    """Escape spaces and parenthesized paths so the markdown link never breaks."""
    url = url.replace(" ", "%20")
    if "(" in url or ")" in url:
        url = f"<{url}>"
    return url


def _blockquote(text: str) -> str:
    """Render the take as a markdown blockquote so it visually pops."""
    return "\n".join(f"> {line}".rstrip() for line in text.splitlines())


def _footer(author: dict | None, t: dict) -> str:
    """Generation stamp plus curator attribution with profile links."""
    author = author or {}
    stamp = utc_now().strftime("%Y-%m-%d %H:%M UTC")
    repo = author.get("repository") or ""
    repo_link = f"[tech-news-curator]({repo})" if repo else "[tech-news-curator]"
    generated = t["generated"].replace("__REPO__", repo_link).replace("__STAMP__", stamp)
    lines = [f"*{generated}*"]
    name = author.get("name")
    if name:
        profile_links = " | ".join(
            f"[{label}]({author[key]})"
            for label, key in (("LinkedIn", "linkedin"), ("GitHub", "github"))
            if author.get(key)
        )
        attribution = f"**{name}**" + (f" | {profile_links}" if profile_links else "")
        lines.append(f"{t['footer_by']} {attribution}")
    return "---\n\n" + "\n\n".join(lines) + "\n"
